version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  webapp: #name of the second service
    build: . # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database
    depends_on:
      - database  

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
